/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: d33a900f2deb5ce2d0819ebe5b5d3130)
// Runtime types generated with workerd@1.20250422.0 2025-03-01 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		NEXTJS_ENV: string;
		JWT_SECRET: string;
		RESEND_API_KEY: string;
		RESEND_EMAIL_FROM: string;
		DB: D1Database;
		ASSETS: Fetcher;
	}
}
declare global {
  interface CloudflareEnv {
    /** D1 database binding */
    DB: D1Database;
    /** Resend API key used for transactional emails */
    RESEND_API_KEY: string;
    /** From address for Resend */
    RESEND_EMAIL_FROM: string;
    /** JWT signing secret */
    JWT_SECRET: string;
    /** Google OAuth client ID */
    GOOGLE_CLIENT_ID: string;
    /** Google OAuth client secret */
    GOOGLE_CLIENT_SECRET: string;
    /** Base URL for the main application */
    APP_BASE_URL: string;
    /** Base URL for the auth worker */
    AUTH_BASE_URL: string;
  }
}

export {}; // ensure this file is treated as a module
